CREATE DATABASE IF NOT EXISTS Academic_DB;
USE Academic_DB;

CREATE TABLE IF NOT EXISTS Department (
  DeptID INT PRIMARY KEY AUTO_INCREMENT,
  DeptName VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Courses (
  CourseID INT PRIMARY KEY AUTO_INCREMENT,
  CourseName VARCHAR(100) NOT NULL,
  DeptID INT,
  Semester INT,
  FOREIGN KEY (DeptID) REFERENCES Department(DeptID)
);

CREATE DATABASE IF NOT EXISTS Student_DB;
USE Student_DB;

CREATE TABLE IF NOT EXISTS Students (
  StudentID INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL,
  Gender CHAR(1),
  DeptID INT,
  Email VARCHAR(100) UNIQUE,
  Phone VARCHAR(20),
  DOB DATE,
  FOREIGN KEY (DeptID) REFERENCES Academic_DB.Department(DeptID)
);

CREATE TABLE IF NOT EXISTS Enrollment (
  EnrollID INT PRIMARY KEY AUTO_INCREMENT,
  StudentID INT,
  CourseID INT,
  Semester INT,
  Grade VARCHAR(4),
  FOREIGN KEY (StudentID) REFERENCES Students(StudentID),
  FOREIGN KEY (CourseID) REFERENCES Academic_DB.Courses(CourseID)
);
